rework of the control script
Armandpl/furuta pull request #45
Opened 2024-01-12 23:24 UTC by pierfabre

2024-01-12 23:24 UTC, pierfabre commented
ready for first round of review  @Armandpl 
Also what do you think of moving robot.py in robot/software?

2024-01-14 09:49 UTC, Armandpl requested changes
- need to move the library code to the furuta package
- later we might also want to move from manual instantiation from json files to using hydra but for now that's 100% ok
apart from that lgtm <3

2024-01-14 09:49 UTC, Armandpl commented on scripts/control.py
> +matplotlib.use("TkAgg")
maybe investigate why we need that?

2024-01-14 09:49 UTC, Armandpl commented on scripts/control.py
> +    input()
add a message so that the user knows he should press a key

2024-01-14 09:49 UTC, Armandpl commented on robot/software/controllers.py
I think this belong to the furuta_gym package which we should rename furuta. This way we can ship all of the code to pypi.
I think the robot directory should contain only what's needed for the physical robot. library and control code should be in the python package.

2024-01-14 09:53 UTC, Armandpl commented on robot/software/controllers.py
i think the pattern for a user of the robot should be to create their own project, pip install furuta then setup their own experiments.

2024-01-14 10:04 UTC, Armandpl commented on scripts/control.py
> +    input()
when this was in a notebook it was obvious bc a modal would pop up, that's not longer the case in a script

2024-01-14 10:05 UTC, pierfabre commented on scripts/control.py
> +matplotlib.use("TkAgg")
Will do during the test on the real robot

2024-01-14 10:06 UTC, pierfabre commented on robot/software/controllers.py
Discussed IRL I'm ok with this

2024-01-14 11:02 UTC, pierfabre commented on scripts/control.py
> +matplotlib.use("TkAgg")
Tested, work without, don't know what happened last time, rm this part

2024-01-14 11:21 UTC, Armandpl approved these changes

2024-01-14 11:21 UTC, merged